### ISSUE TITLE
How to import tasks to broker?

### ISSUE THREAD

**Issue by dinosaurtirex** [taskiq-python/taskiq#129] opened 2023-05-12 16:58 UTC
For now all options what i found it's to do something like this:

```
# broker.py

broker = AioPikaBroker(
     "amqp://guest:guest@localhost:5672",
     result_backend=RedisAsyncResultBackend("redis://localhost:6379"),
)

@broker.task
async def some_func(): ...

@broker.task
async def some_func(): ...

@broker.task
async def some_func(): ...

@broker.task
async def some_func(): ...
```

Is there an option to import all tasks or declare them in another file? 
Something like this:

```
TASKS = {
   "tasks": [
      "app_one.tasks",
      "app_two.tasks",
     ...
   ]
}

broker = AioPikaBroker(
     "amqp://guest:guest@localhost:5672",
     result_backend=RedisAsyncResultBackend("redis://localhost:6379"),
    tasks = TASKS
)
```

**Comment by dinosaurtirex** [comment] 2023-05-12 17:18
So the problem for me it's like if i have 1000 of tasks, it will be just in one file, what is not best decision

**Comment by s3rius** [comment] 2023-05-12 19:04
Of course you can import tasks. You can name files like tasks.py and enable `--fs-discover` to search for all `tasks.py` files and importing them. 

If you want to change name of files taskiq is going to look for, you can provide it with `--tasks-pattern` with your name pattern. 

```bash
taskiq worker a:broker --fs-discover --tasks-pattern "tasks_*.py"
```
This command is going to automatically import all files named `task_*.py` from all child directories.

**Comment by s3rius** [comment] 2023-05-12 19:05
If the problem is resolved, don't forget to close the issue. 

If you find your experience with task pleasant, you can help us improve, by hitting the star button and giving us feedback here in the [discussion](https://github.com/orgs/taskiq-python/discussions/69).

**Comment by dinosaurtirex** [comment] 2023-05-12 19:43
> Thanks for raising your issue. You can easily discover and import tasks. You can name files with like `tasks.py` and enable `--fs-discover` to search for all `tasks.py` files and import them on startup.
> 
> If you want to change name of files taskiq is going to look for, you can provide it with `--tasks-pattern` with your name pattern.
> 
> ```shell
> taskiq worker a:broker --fs-discover --tasks-pattern "tasks_*.py"
> ```
> 
> This command is going to automatically import all files named `task_*.py` from all child directories.

Thank you very much!

**Closed** 2023-05-12 19:43 UTC

**Comment by dinosaurtirex** [comment] 2023-05-13 15:38
> Thanks for raising your issue. You can easily discover and import tasks. You can name files with like `tasks.py` and enable `--fs-discover` to search for all `tasks.py` files and import them on startup.
> 
> If you want to change name of files taskiq is going to look for, you can provide it with `--tasks-pattern` with your name pattern.
> 
> ```shell
> taskiq worker a:broker --fs-discover --tasks-pattern "tasks_*.py"
> ```
> 
> This command is going to automatically import all files named `task_*.py` from all child directories.

Can you please provide some example of tasks.py file? Right now im using something like this:

```
# tasks.py 

from task_queue_blueprint.broker import broker 

@broker.task
async def task_a(*args):
    ...


@broker.task
async def task_b(*args):
  ...
```

Run broker like this:

```
taskiq worker broker:broker --fs-discover
```

And got this error:

```
task "task_a" is not found. Maybe you forgot to import it?
```
